plugins {
    // No separate org.jetbrains.kotlin.android plugin: AGP 9 has built-in Kotlin support and
    // registers the `kotlin` extension itself. Applying the standalone plugin fails with
    // "Cannot add extension with name 'kotlin'".
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.bhashabridge.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "com.bhashabridge.app"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        // NOT carried from v3.4.1: multiDexEnabled / androidx.multidex. minSdk is 24, and
        // ART has had native multidex since 21 — AGP warns the library is unnecessary.
        // v3.4.1 carried it as legacy baggage.

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }

    // BuildConfig is not generated by default since AGP 8. logDebug() compiles itself out of
    // release builds via BuildConfig.DEBUG, so this is load-bearing, not boilerplate.
    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    // Carried from v3.4.1. ONNX Runtime and Vosk each ship their own copies of some
    // .so files; without pickFirsts the merge fails on duplicate native libs.
    packaging {
        resources {
            excludes += setOf(
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE.txt",
                "META-INF/LICENSE",
                "META-INF/NOTICE",
                "META-INF/*.kotlin_module",
                "META-INF/DEPENDENCIES",
            )
        }
        jniLibs {
            pickFirsts += setOf(
                "**/libonnxruntime.so",
                "**/libonnxruntime4j_jni.so",
                "**/libvosk.so",
                "**/libjnidispatch.so",
            )
        }
    }

    // Carried from v3.4.1 (aaptOptions -> androidResources in AGP 9).
    // ONNX Runtime mmaps model files from disk; a compressed asset cannot be mmapped and
    // would force a full decompress-to-memory on every load.
    androidResources {
        noCompress += setOf("onnx", "bin", "pb")
    }

    // Carried from v3.4.1. Universal APK disabled: a single APK carrying both ABIs plus
    // ~636 MB of models is not installable on the target device.
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "armeabi-v7a")
            isUniversalApk = false
        }
    }
}

dependencies {
    // --- ML stack: versions pinned to v3.4.1's proven set ---
    implementation(libs.onnxruntime.android)
    implementation(libs.vosk.android)
    implementation(libs.kotlinx.coroutines.android)

    // --- AndroidX / Material ---
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.material)

    // --- Lifecycle: required by the Phase 6 ViewModel + process-scoped engine ownership ---
    // runtime-ktx supplies lifecycleScope / repeatOnLifecycle, how the Phase 9 UI collects state.
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.process)

    // --- Test ---
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
}
